<div>
	<h3>
		<?php echo __( 'Your Quizzes', Thrive_Quiz_Builder::T ); ?>&nbsp;&nbsp;
		<a class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-purple tvd-btn-small tqb-add-quiz-dashboard">
			<?php echo __( 'Add New', Thrive_Quiz_Builder::T ); ?>
		</a>
	</h3>
</div>
<div id="tqb-no-quiz-text" class="tqb-no-quiz-wrapper">
	<p>
		<?php echo __( 'You have no quizzes yet. Click the Add New Quiz button to get started or', Thrive_Quiz_Builder::T ); ?>
		<a href="<?php echo Thrive_Quiz_Builder::VIDEO_PLUGIN_DASHBOARD; ?>" class='wistia-popover[height=450,playerColor=2bb914,width=800]'><?php echo __( 'watch a Quick Start Tutorial.', Thrive_Quiz_Builder::T ); ?></a>
	</p>
</div>

<div class="tvd-row" id="tqb-quiz-list">
	<div class="tvd-col tvd-s6 tvd-ms6 tvd-m4 tvd-l3 tqb-add-quiz tvd-pointer">
		<div class="tvd-card tvd-large tvd-card-new tvd-valign-wrapper">
			<div class="tvd-card-content tvd-valign tvd-center-align">
				<i class="tvd-icon-plus tvd-icon-rounded tvd-icon-medium"></i>
				<h4><?php echo __( 'ADD NEW QUIZ', Thrive_Quiz_Builder::T ) ?></h4>
			</div>
		</div>
	</div>
</div>
