<td style="width: 40%;">
	<a href="javascript:void(0)" target="_blank" class="tvd-text-gray">
		<#= test.get('title')==""?"&nbsp;":test.get('title') #>
	</a>
</td>
<td class="tvd-center-align">
	<#= test.get('post_type') #>
</td>
<td>
	<div class="tvd-right">
		<a href="javascript:void(0)"
		   data-id="<#= test.get('post_id') #>"
		   data-title="<#= test.get('title') #>"
		   title="<?php echo __( 'Start another test', THO_TRANSLATE_DOMAIN ) ?>"
		   class="tvd-btn-icon tvd-btn-icon-green  tho-set-another-test tho-small-btn">
			<span class="tho-icon-flask"></span>
				<span class="tvd-on-large-and-down">
					<?php echo __( 'Start another test', THO_TRANSLATE_DOMAIN ) ?>
				</span>
		</a>

		<a href="javascript:void(0)"
		   data-id="<#= test.get('post_id') #>"
		   data-test="<#= test.get('id') #>"
		   data-title="<#= test.get('title') #>"
		   title="<?php echo __( 'Delete tests data', THO_TRANSLATE_DOMAIN ) ?>"
		   class="tvd-btn-icon tvd-btn-icon-red tho-delete-tests-modal tho-small-btn">
			<span class="tvd-icon-trash-o"></span>
				<span class="tvd-on-large-and-down">
					<?php echo __( 'Delete tests data', THO_TRANSLATE_DOMAIN ) ?>
				</span>
		</a>

		<a href="#test/<#= test.get('id') #>" data-id="<#= test.get('id') #>"
		   title="<?php echo __( 'Reports', THO_TRANSLATE_DOMAIN ) ?>"
		   class="tvd-btn-icon tvd-btn-icon-blue tho-small-btn">
			<span class="tho-icon-chart"></span>
			<span class="tvd-on-large-and-down"><?php echo __( 'Reports', THO_TRANSLATE_DOMAIN ) ?></span>
		</a>
	</div>
</td>
