<div class="tvd-col tvo-show-hide-testimonial-info-container">
    <div class="tvd-row tvd-collapse">
        <div class="tvd-col tvd-l1 tvd-s2">
            <input type="checkbox" id="checkbox_testimonial_<#=  testimonial.get('id') #>" data-id="<#= testimonial.get('id') #>"
                   class="tvo-checkbox-testimonial-item"/>
            <label for="checkbox_testimonial_<#= testimonial.get('id') #>" class="tvo-testimonial-item-checkbox"></label>
        </div>
        <div class="tvd-col tvd-l3 tvd-center-align tvd-s10">
            <a href="#testimonials/<#= testimonial.get('id') #>" style="max-width:76px; background-image: url(<#= testimonial.get('picture_url') #>)" class="tvo-profile-picture">
                <img src="<#= testimonial.get('picture_url') #>" width="70" height="70" class="tvo-dummy-image">
            </a>
        </div>
        <div class="tvd-col tvd-l8 tvd-s12">
            <a href="#testimonials/<#= testimonial.get('id') #>">
                <#= testimonial.get('name') #>
            </a>
            <br>
            <span class="tvd-small-text tvo-gray-text"><#= testimonial.get('date') #></span>
            <span class="tvd-small-text tvo-teal-text tvo-show-hide-type-container"><#= testimonial.get('source') #></span>
        </div>
    </div>
</div>
<div class="tvd-col tvd-s3 tvo-show-hide-description-container">
    <span class="tvo-testimonial-title">
        <#= testimonial.get('title') #>
    </span>
    <div class="tvo-testimonial-content-summary">
        <p>
            <#= testimonial.get('summary') #>
        </p>
    </div>
    <div class="tvo-testimonial-content-full tvd-hide">
        <#= testimonial.get('content') #>
    </div>
</div>
<div class="tvd-col tvd-s3 tvo-show-hide-tags-container">
    <div class="tvd-clearfix tvd-hide tvo-testimonial-<#= testimonial.get('id') #>-tag-add-area">
        <div class="tvd-row tvd-collapse tvd-no-mb">
            <div class="tvd-col tvd-s12">
                <div class="tvd-input-field tvd-no-margin">
                    <select id="tvo-testimonial-<#= testimonial.get('id') #>-new-tag" class="tvo-add-tag-autocomplete" multiple="multiple"></select>
                </div>
            </div>
            <div class="tvd-col tvd-s12">
                <a href="javascript:void(0);"
                   class="tvd-waves-effect tvd-waves-light tvd-btn-flat tvd-btn-green tvd-btn-small tvo-add-new-tag-action tvd-margin-top">
					<?php echo __( 'Save', TVO_TRANSLATE_DOMAIN ); ?>
                </a>
            </div>
        </div>
    </div>
    <div class="tvo-testimonial-<#= testimonial.get('id') #>-tag-display-area">
        <div class="tvd-clearfix">
            <#
                    var tags = testimonial.get('tags');
                    if( tags.length > 0 ){
                for(var i=0; i < tags.length ; i++){ #>
                <div class="tvo-testimonial-custom-tag-<#= testimonial.get('id') #>-<#= tags[i].id #> tvd-chip tvo-testimonial-custom-tag">
                    <#= tags[i].text #></#>
                    &nbsp;
                    <a href="javascript:void(0);" class="tvo-remove-testimonial-tag tvd-icon-close2" data-tag-id="<#= tags[i].id #>"
                       data-testimonial-id="<#= testimonial.get('id') #>"></a>&nbsp;&nbsp;</div>
                <#
                        }
                        }else{
                        #>
                    <i class="tvd-small-text tvo-gray-text">
                        <#= ThriveOvation.translations.untagged_testimonial #>
                    </i>
                    <#
                            }
                            #>
        </div>
        <a href="javascript:void(0);" class="tvd-waves-effect tvd-waves-light tvd-btn-flat tvd-btn-flat-blue tvd-btn-small tvo-add-new-tag">
            <span class="tvd-icon-plus tvd-icon-xsmall"></span>
			<?php echo __( 'ADD TAG', TVO_TRANSLATE_DOMAIN ); ?>
        </a>
    </div>
</div>
<div class="tvd-col tvd-s2 tvo-show-hide-status-container">
    <div class="tvd-no-margin">
        <select class="tvo-testimonial-status-change tvo-status-select tvo-testimonial-status-<#= testimonial.get('status') #>"
                data-id="<#= testimonial.get('id') #>" data-value="<#= testimonial.get('status') #>">
            <option value="<?php echo TVO_STATUS_READY_FOR_DISPLAY; ?>"
            <# if(testimonial.get('status') == ThriveOvation.const.status.ready_for_display){ #> selected="selected"
                <# }#> ><?php echo __( 'Ready for Display', TVO_TRANSLATE_DOMAIN ); ?></option>
                    <option value="<?php echo TVO_STATUS_AWAITING_APPROVAL; ?>"
                    <# if(testimonial.get('status') == ThriveOvation.const.status.awaiting_approval){ #> selected="selected"
                        <# }#> ><?php echo __( 'Awaiting Approval', TVO_TRANSLATE_DOMAIN ); ?></option>
                            <option value="<?php echo TVO_STATUS_AWAITING_REVIEW; ?>"
                            <# if(testimonial.get('status') == ThriveOvation.const.status.awaiting_review){ #> selected="selected"
                                <# }#>><?php echo __( 'Awaiting Review', TVO_TRANSLATE_DOMAIN ); ?></option>
                                    <option value="<?php echo TVO_STATUS_REJECTED; ?>"
                                    <# if(testimonial.get('status') == ThriveOvation.const.status.rejected){ #> selected="selected"
                                        <# }#>><?php echo __( 'Rejected', TVO_TRANSLATE_DOMAIN ); ?></option>
        </select>
    </div>
</div>
<div class="tvd-col tvd-s1">
    <div class="tvd-right">
        <a href="javascript:void(0)" data-id="<#= testimonial.get('id') #>"
           class="tvd-tooltipped tvo-testimonial-duplicate tvd-btn-icon-only tvd-btn-icon-only-blue tvd-margin-right-small"
           data-position="top"
           data-tooltip="<?php echo __( 'Duplicate', TVO_TRANSLATE_DOMAIN ); ?>">
            <span class="tvd-icon-copy"></span>
        </a>
        <a href="#testimonials/<#= testimonial.get('id') #>" data-id="<#= testimonial.get('id') #>"
           class="tvd-tooltipped tvo-testimonial-edit tvd-btn-icon-only tvd-btn-icon-only-blue tvd-margin-right-small"
           data-position="top"
           data-tooltip="<?php echo __( 'Edit', TVO_TRANSLATE_DOMAIN ); ?>">
            <span class="tvd-icon-pencil"></span>
        </a>
        <a href="javascript:void(0)" data-title="<#= testimonial.get('name') #>" data-id="<#= testimonial.get('id') #>"
           class="tvd-tooltipped tvd-btn-icon-only tvd-btn-icon-only-red tvo-delete-testimonial-modal"
           data-position="top"
           data-tooltip="<?php echo __( 'Delete', TVO_TRANSLATE_DOMAIN ); ?>">
            <span class="tvd-icon-trash-o"></span>
        </a>
    </div>
</div>
