<div class="tvd-row tvd-collapse tvd-no-mb">
	<div class="tvo-testimonial-author-image tvd-col tvd-s2 tvd-center-align">
		<img width="180" src="<#= ThriveOvation.testimonial_image_placeholder #>" class="tvo-rounded-img">
		<br>
		<a href="javascript:void(0)" class="tvd-small-text"
		   id="tvo-upload-testimonial-image"><?php echo __( 'UPLOAD PICTURE', TVO_TRANSLATE_DOMAIN ); ?></a>
	</div>
	<div class="tvo-testimonial-data tvd-col tvd-s10"
	     data-id="">
		<div class="tvd-v-spacer"></div>
		<div class="notice notice-warning is-dismissible">
			<p><?php echo __( 'If you import testimonials from pages with restricted content, the image will not be available.', TVO_TRANSLATE_DOMAIN ); ?></p>
		</div>

		<div class="tvd-row">
			<div class="tvd-col tvd-s12">
				<div class="tvd-input-field tvo-title">
					<input type="text" id="tvo-title" class="tvd-validate tvo-social-field" value=""/>
					<label
						for="tvo-title"
						data-error="<?php echo __( 'Please fill in the title field', TVO_TRANSLATE_DOMAIN ); ?>"><?php echo __( 'Title', TVO_TRANSLATE_DOMAIN ); ?></label>
				</div>
			</div>
		</div>
		<div class="tvd-row">
			<div class="tvd-col tvd-s6">
				<div class="tvd-input-field tvo-author-name">
					<input type="text" id="tvo-author-name" class="tvd-validate tvo-social-field" value=""/>
					<label for="tvo-author-name"
					       data-error="<?php echo __( 'Please fill in the name field', TVO_TRANSLATE_DOMAIN ); ?>"><?php echo __( 'Full Name', TVO_TRANSLATE_DOMAIN ); ?></label>
				</div>
			</div>
			<div class="tvd-col tvd-s6">
				<div class="tvd-input-field tvo-author-ocupation">
					<input type="text" id="tvo-author-role" class="tvd-validate tvo-social-field" value=""/>
					<label
						for="tvo-author-role"
						data-error="<?php echo __( 'Please fill in the occupation field', TVO_TRANSLATE_DOMAIN ); ?>"><?php echo __( 'Role/Occupation', TVO_TRANSLATE_DOMAIN ); ?></label>
				</div>
			</div>
		</div>
		<div class="tvd-row">
			<div class="tvd-col tvd-s6">
				<div class="tvd-input-field tvo-author-email tvo-author-handle">
					<input type="text" id="tvo-author-email" class="tvd-validate tvo-social-field" value=""/>
					<label
						for="tvo-author-email"
						data-error-twitter="<?php echo __( 'Please fill in a Twitter handle', TVO_TRANSLATE_DOMAIN ); ?>"
						data-content-twitter="<?php echo __( 'Twitter handle', TVO_TRANSLATE_DOMAIN ); ?>"
						data-content-facebook="<?php echo __( 'Facebook ID', TVO_TRANSLATE_DOMAIN ); ?>"
						data-error-facebook="<?php echo __( 'Please fill in the Facebook ID', TVO_TRANSLATE_DOMAIN ); ?>"
						data-error="<?php echo __( 'Please fill in a valid email address', TVO_TRANSLATE_DOMAIN ); ?>">
						<?php echo __( 'Email Address', TVO_TRANSLATE_DOMAIN ); ?>
					</label>
				</div>
			</div>
			<div class="tvd-col tvd-s6">
				<div class="tvd-input-field tvo-author-website">
					<input type="text" id="tvo-author-website" class="tvd-validate tvo-social-field" value=""/>
					<label
						for="tvo-author-website"
						data-error="<?php echo __( 'Please fill in a valid website URL', TVO_TRANSLATE_DOMAIN ); ?>"><?php echo __( 'Website URL', TVO_TRANSLATE_DOMAIN ); ?></label>
				</div>
			</div>
		</div>
		<div class="tvd-row tvo-testimonial-tags">
			<div class="tvd-col tvd-s12">
				<h4 class="tvd-no-margin">
					<?php echo __( 'Tags', TVO_TRANSLATE_DOMAIN ); ?>
				</h4>
				<div class="tvo-testimonial-add-tags tvo-edit-testimonial-tags-container">
					<select id="tvo-social-media-new-tag-modal" class="tvo-add-tag-autocomplete"></select>
				</div>
				<div class="tvo-testimonial-existing-tags"></div>
			</div>
		</div>
	</div>
</div>
<div class="tvo-testimonial-content">
	<?php wp_editor( '', 'tvo-testimonial-content-tinymce', array(
		'quicktags'     => false,
		'media_buttons' => false,
	) ) ?>
</div>
