<div class="tvd-modal-content">
	<a href="javascript:void(0)" class="tvd-modal-action tvd-modal-close tvd-modal-close-x">
		<i class="tvd-icon-close2"></i>
	</a>
	<?php include TVO_ADMIN_PATH . '/views/template/testimonials/base.phtml'; ?>
</div>
<div class="tvd-modal-footer">
	<div class="tvd-row">
		<div class="tvd-col tvd-s12 tvd-m6">
			<a class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-gray tvd-modal-close"
			   href="javascript:void(0);"><?php echo __( 'Close', TVO_TRANSLATE_DOMAIN ); ?></a>
			</a>
		</div>
		<div class="tvd-col tvd-s12 tvd-m6">
			<a class="tvo-save-new-testimonial tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green tvd-right"
			   href="javascript:void(0);"><?php echo __( 'Add testimonial', TVO_TRANSLATE_DOMAIN ); ?></a>
			</a>
		</div>
	</div>
</div>
