<div class="tvd-col tvd-s1">
		<span class="tge-sort-handle tvd-move">
			<span class="tvd-icon-handle"></span>
		</span>
</div>
<div class="tvd-col tvd-s8">
	<div class="tvd-input-field">
		<input placeholder="<?php echo __( 'Answer', Thrive_Graph_Editor::T ) ?>" type="text" value="<#= item.get('text') #>" data-bind="text">
	</div>
</div>
<div class="tvd-col tvd-s2">
	<div class="tvd-input-field">
		<input maxlength="6" placeholder="<?php echo __( 'Points' ) ?>" type="number" value="<#= item.get('points') ? item.get('points') : 1 #>">
	</div>
</div>
<div class="tvd-col tvd-s1">
	<span class="tvd-icon-trash-o tvd-pointer"></span>
</div>
