<div class="tvd-modal-content">
	<h3 class="tvd-modal-title"><?php echo __( 'Email Delivery Setup', TVO_TRANSLATE_DOMAIN ); ?></h3>
	<div class="tvo-delivery-step1 tvd-modal-step">
		<p>
			<?php echo __( 'Select the email delivery service you want to use for the Asset Delivery feature. Integrating with one of these services ensures that your emails get delivered without you needing to deal with email server setups and spam protection', TVO_TRANSLATE_DOMAIN ) ?>
		</p>
		<p class="tvd-center-align tvd-text-green">
			<strong><?php echo __( 'Select to continue', TVO_TRANSLATE_DOMAIN ); ?></strong></p>
		<div class="tvd-row" id="tvo-connections-list"></div>
		<button class="tvd-btn-flat-blue tvo-asset-close tvd-btn-flat tvd-waves-effect">‹ Back</button>
	</div>
	<div class="tvo-delivery-step2 tvd-modal-step">
		<?php foreach ( Thrive_Dash_List_Manager::getAvailableAPIsByType( false, array( 'email' ) ) as $key => $api ) : ?>
			<?php /** @var $api Thrive_Dash_List_Connection_Abstract */ ?>
			<div class="tvo-connection-form" data-key="<?php echo $key ?>" style="">
				<?php echo $api->outputSetupForm(); ?>
			</div>
		<?php endforeach; ?>
	</div>

	<div class="tvo-delivery-success tvd-modal-step">
		<div class="tvd-row">
			<div class="tvd-col tvd-s10 tvd-offset-s1 tvd-center-align">
				<img src="<?php echo plugins_url( 'thrive-leads/admin/img/succes_image.png' ) ?>">
				<p><?php echo __( 'You have successfully connected to', 'thrive-leads' ) ?> <span
						class="tvo-connection-name-success"></span> <?php echo __( 'for your email delivery', 'thrive-leads' ) ?>
					!</p>
			</div>
		</div>
		<div class="tvd-modal-footer-inside">
			<div class="tvd-row">
				<div class="tvd-col tvd-s6 tvd-offset-s3">
					<button
						class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green tvd-full-btn tvo-asset-close">
						<?php echo __( 'Save & Continue', 'thrive-leads' ) ?>
					</button>
				</div>
			</div>
		</div>
	</div>
</div>
