<div class="tvd-row">
	<div class="tvd-col tvd-s4">
		<h3 class="tvd-title"><?php echo __( 'Import testimonials from social media', TVO_TRANSLATE_DOMAIN ); ?></h3>
	</div>
	<div class="tvd-col tvd-s8">
		<a target="_blank" href="<?php echo admin_url( 'admin.php?page=tve_dash_api_connect' ); ?>" class="tvd-waves-light tvd-btn tvd-btn-blue tvd-btn-small">
			<?php echo __( 'Set up integrations', TVO_TRANSLATE_DOMAIN ); ?>
		</a>
	</div>
</div>

<div class="tvd-row">
	<div class="tvd-col tvd-s12">
		<span>
			<?php echo __( 'You don\'t have any social media integration set up. You set up api connections', TVO_TRANSLATE_DOMAIN ); ?>
			<a target="_blank" href="<?php echo admin_url( 'admin.php?page=tve_dash_api_connect' ); ?>">
				<?php echo __( 'here', TVO_TRANSLATE_DOMAIN ); ?>.
			</a>
		</span>
	</div>
</div>

