<div class="tge-form-image-wrapper"></div>
<a class="tge-add-image" href="javascript:void(0)"><?php echo __( 'Add Image [Optional]', Thrive_Graph_Editor::T ) ?></a>
<a class="tge-remove-image" style="display: none" href="javascript:void(0)"><?php echo __( 'Remove', Thrive_Graph_Editor::T ) ?></a>
<a class="tge-change-image" style="display: none;" href="javascript:void(0)"><?php echo __( 'Change', Thrive_Graph_Editor::T ) ?></a>