<div class="tge-modal-step">
	<div class="tvd-modal-content">
		<h3 class="tvd-modal-title"><?php echo __( 'Select question type', Thrive_Graph_Editor::T ) ?></h3>
		<hr>
		<p class="tqb-modal-subtitle"><?php echo __( 'Select question type:', Thrive_Graph_Editor::T ) ?></p>
		<div id="tge-question-types" class="tvd-row tvd-collapse"></div>
	</div>
	<div class="tvd-modal-footer">
		<div class="tvd-row">
			<div class="tvd-col tvd-s12 tvd-m6">
				<a href="javascript:void(0)"
				   class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-waves-effect tvd-modal-close">
					<?php echo __( 'Cancel', Thrive_Graph_Editor::T ) ?>
				</a>
			</div>
			<div class="tvd-col tvd-s12 tvd-m6">
				<a href="javascript:void(0)"
				   class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-purple tvd-right tge-modal-next-step">
					<?php echo __( 'Continue', Thrive_Graph_Editor::T ) ?>
				</a>
			</div>
		</div>
	</div>
</div>

<div class="tge-modal-step">
	<div class="tvd-modal-content">
		<h3 class="tvd-modal-title"><?php echo __( 'Add Question', Thrive_Graph_Editor::T ) ?></h3>
		<div id="tge-question-form"></div>
	</div>
	<div class="tvd-modal-footer">
		<div class="tvd-row">
			<div class="tvd-col tvd-s12 tvd-m6">
				<a href="javascript:void(0)"
				   class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-waves-effect tge-modal-prev-step">
					<?php echo __( 'Back', Thrive_Graph_Editor::T ) ?>
				</a>
			</div>
			<div class="tvd-col tvd-s12 tvd-m6">
				<a href="javascript:void(0)"
				   class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-purple tvd-right tvd-modal-submit">
					<?php echo __( 'Save', Thrive_Graph_Editor::T ) ?>
				</a>
			</div>
		</div>
	</div>
</div>
