<div class="tvd-modal-content">
    <h4><?php echo __( 'Delete Question', Thrive_Graph_Editor::T ) ?></h4>

    <p><?php echo __( 'Are you sure that you want to remove this question? It will be permanently removed.', Thrive_Graph_Editor::T ) ?></p>
</div>
<div class="tvd-modal-footer">
    <div class="tvd-row">
        <div class="tvd-col tvd-s12 tvd-m6">
            <a href="javascript:void(0)"
               class="tvd-btn-flat tvd-btn-flat-primary tvd-btn-flat-light tvd-modal-close tvd-waves-effect"><?php echo __( 'Cancel', Thrive_Graph_Editor::T ) ?></a>
        </div>
        <div class="tvd-col tvd-s12 tvd-m6">
            <a href="javascript:void(0)"
               class="tvd-waves-effect tvd-waves-light tvd-btn-flat tvd-btn-flat-primary tvd-btn-flat-light tvd-right tve-confirm-delete-action"><?php echo __( 'Delete', Thrive_Graph_Editor::T ) ?></a>
        </div>
    </div>
</div>
