<div class="tvd-row">
	<div class="tvd-col tvd-s12">
		<h3 class="tvd-title"><?php echo __( "New Headline Split Test: Create Your Variations", THO_TRANSLATE_DOMAIN ); ?></h3>
		<div class="tvd-v-spacer"></div>
		<div class="tho-posts-list-variations"></div>
		<div class="tvd-v-spacer"></div>
	</div>
	<div class="tvd-col tvd-s12">
		<a href="javascript:void(0);"
		   class="tho-step1-back tvd-btn-flat tvd-btn-flat-primary tvd-btn-flat-dark tvd-waves-effect">&laquo; <?php echo __( "Back to: Choose posts", THO_TRANSLATE_DOMAIN ); ?></a>
		<a href="javascript:void(0);"
		   class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green tvd-right tho-determine-test-criteria"><?php echo __( "Next step: Determine test criteria", THO_TRANSLATE_DOMAIN ); ?></a>
	</div>
</div>
