<div class="tvd-card-content">
	<div class="tvd-row tvd-no-margin">
		<div class="tvd-col tvd-s9 tvd-offset-s1">
			<div class="tvd-row tvd-no-margin">
				<div class="tvd-col tvd-s3">
					<div class="tho-vertical-align tvd-right-align">
						<h5><?php echo __( "Current title (control)", THO_TRANSLATE_DOMAIN ); ?></h5>
					</div>
				</div>
				<div class="tvd-col tvd-s8">
					<div class="tvd-input-field">
						<input type="text" class="tho-control" value="<#= test.get('title') #>" disabled="disabled"/>
					</div>
				</div>
				<div class="tvd-col tvd-s1">
					&nbsp;
				</div>
			</div>
			<div class="tho-variation-items"></div>

			<div class="tvd-row tvd-no-margin">
				<div class="tvd-col tvd-s11">
					<a href="javascript:void(0);" class="tvd-waves-effect tvd-waves-light tvd-btn-flat tvd-btn-flat-teal tvd-btn-small tho-add-variation tvd-right"><span
							class="tvd-icon-plus tvd-icon-xsmall"></span>&nbsp;<?php echo __( "Add variation", THO_TRANSLATE_DOMAIN ); ?>
					</a>
				</div>
			</div>
		</div>
	</div>
</div>
