<div class="tvd-row">
	<div class="tvd-col tvd-s3">
		<div class="tho-vertical-align tvd-right-align">
			<h5><?php echo __( "Variation: ", THO_TRANSLATE_DOMAIN ); ?></h5>
		</div>
	</div>
	<div class="tvd-col tvd-s8">
		<div class="tvd-input-field ">
			<input type="text" class="tho-variation tvd-tooltipped" data-tooltip="<?php echo __( "Press enter to save the variation and tab to go to the next post.", THO_TRANSLATE_DOMAIN ); ?>"
			       placeholder="<?php echo __( "This is a post headline variation", THO_TRANSLATE_DOMAIN ); ?>" value="<#= variation #>"/>
		</div>
	</div>
	<div class="tvd-col tvd-s1">
		<div class="tho-vertical-align">
			<a href="javascript:void(0);" class="tho-delete-variation tvd-btn-icon-only tvd-btn-icon-only-red">
				<i class="tvd-icon-trash-o"></i>
			</a>
		</div>
	</div>
</div>
