<div class="tvo-spacer"></div>
<h5 class="tvo-center-text">
	<?php echo __( 'Choose an existing display template below or create a new list of testimonials', TVO_TRANSLATE_DOMAIN ); ?>
</h5>
<div class="tvo-spacer"></div>
<div id="tvo-testimonial-shortcode-list">
	<a class="tvo-shortcode-box tvo-create-testimonial-list" href="#pre-select">
		<div class="tvo-card tvo-card-xsmall">
			<div class="tvo-card-content">
				<span class="tvo-f-icon-add tvo-add-testimonial"></span>
				<?php echo __( 'Create New Display Template', TVO_TRANSLATE_DOMAIN ); ?>
			</div>
		</div>
	</a>
</div>
