<div class="tvo-row">
	<div class="tvo-col tvo-s8">
		<h4>
			<?php echo __( 'Drag and drop testimonials into the desired order below', TVO_TRANSLATE_DOMAIN ); ?>
		</h4>
	</div>
	<div class="tvo-col tvo-s4">
		<button class="tve_editor_button tve_editor_button_success tve_right tvo-randomize-testimonials">
			<?php echo __( 'Randomize', TVO_TRANSLATE_DOMAIN ); ?>
		</button>
	</div>
</div>
<div class="tvo-testimonials-list-order ui-sortable"></div>
