<h3 class="tvo_tags_count" style="text-align: center;">
	<?php echo __( 'You have <b>0</b> tags on your list', TVO_TRANSLATE_DOMAIN ); ?>
</h3>

<div class="tve_scTC tve_scTC1" style="display: block;">
	<div id="tvo-tags-list" class="tvo-row"></div>
	<div class="tvo-row tvo-collapse">
		<div class="tvo-col tvo-s4">
			<p>
				<span class="tvo-margin-right-small"></span>
				<?php echo __( 'Max number of testimonials', TVO_TRANSLATE_DOMAIN ) ?>
			</p>
		</div>
		<div class="tvo-col tvo-s6">
			<input class="tvo_config_field tve_lightbox_input tvo_max_testimonials" type="text" value="<#= max_testimonials #>">
		</div>
	</div>
</div>
<div class="tve_clear" style="height: 15px;"></div>

