<h3 class="tvo_testimonials_count" style="text-align: center;">
	<?php echo __( 'You have <b>0</b> testimonials on your list', TVO_TRANSLATE_DOMAIN ); ?>
</h3>

<div class="tve_scTC tve_scTC1" style="display: block;">
	<div class="tve_clear" style="height: 15px;"></div>
	<div class="tvo-row tvo-no-mb">
		<div class="tvo-col tvo-s2">
			<div class="tve_lightbox_select_holder">
				<select class="tvo-filter-image" id="tvo-filter-image">
					<option value="select-image"><?php echo __( 'Image Filter', TVO_TRANSLATE_DOMAIN ); ?></option>
					<option value="with-image"><?php echo __( 'With Image', TVO_TRANSLATE_DOMAIN ); ?></option>
					<option value="without-image"><?php echo __( 'Without Image', TVO_TRANSLATE_DOMAIN ); ?></option>
					<option value="any"><?php echo __( 'Any', TVO_TRANSLATE_DOMAIN ); ?></option>
				</select>
			</div>
		</div>
		<div class="tvo-col tvo-s2">
			<div class="tve_lightbox_select_holder">
				<select class="tvo-filter-title" id="tvo-filter-title">
					<option value="select-title"><?php echo __( 'Title Filter', TVO_TRANSLATE_DOMAIN ); ?></option>
					<option value="with-title"><?php echo __( 'With Title', TVO_TRANSLATE_DOMAIN ); ?></option>
					<option value="without-title"><?php echo __( 'Without Title', TVO_TRANSLATE_DOMAIN ); ?></option>
					<option value="any"><?php echo __( 'Any', TVO_TRANSLATE_DOMAIN ); ?></option>
				</select>
			</div>
		</div>
		<div class="tvo-col tvo-s3">
			<div class="tve_lightbox_input_holder word_count_lightbox_holder">
				<input type="checkbox" value="0" name="tvo-testimonial-word-count-check" id="tvo-testimonial-word-count-check">
				<label for="tvo-testimonial-word-count-check">
					<?php echo __( 'Word count from', TVO_TRANSLATE_DOMAIN ); ?>
				</label>
				<input type="text" name="from" value="" class="tvo-input-range" id="tvo-from-value" data-field="time"/>
				<label><?php echo __( 'to', TVO_TRANSLATE_DOMAIN ); ?></label>
				<input type="text" name="to" value="" class="tvo-input-range" id="tvo-to-value"/>
				<div class="tvo-filter-error-message"></div>
			</div>
		</div>
		<div class="tvo-col tvo-s2">
			<select id="tvo-filter-tags" class="tvo-add-tag-autocomplete"></select>
		</div>
		<div class="tvo-col tvo-s2">
			<input type="text" class="tvo-testimonials-search tve_lightbox_input" placeholder="<?php echo __( 'Search', TVO_TRANSLATE_DOMAIN ); ?>"/>
		</div>
		<div class="tvo-col tvo-s6">
			<div class="tve_lightbox_input_holder">
				<input type="checkbox" value="0" name="tvo-testimonial-select-all" id="tvo-testimonial-select-all">
				<label for="tvo-testimonial-select-all">
					<?php echo __( 'Select all', TVO_TRANSLATE_DOMAIN ); ?>
				</label>
			</div>
		</div>
	</div>
	<div class="tvo-spacer"></div>
	<div id="tvo-testimonials-list"></div>
	<div class="tvo-top-pagination tve_clearfix"></div>
	<div class="tve_clear" style="height: 15px;"></div>
</div>

