<div class="tvo-row tvo-collapse">
	<div class="tvo-col tvo-s8">
		<strong class="tvo-testimonial-title tvo-testimonial-list-title">
			<#= this.model.get('name') #>
		</strong>
	</div>
	<div class="tvo-col tvo-s4">
		<div class="tvo-right">
			<a class="tve_editor_button tve_editor_button_default tve_editor_button_small tvo-margin-right-small" href="#select-<#= this.model.get('testimonials')>0?'testimonials':'tags' #><#= '/'+this.model.get('id') #>">
				<span class="tvo-f-icon-edit-testimonial"></span>
			</a>
			<div data-id="<#= this.model.get('id') #>" class="tve_editor_button tve_editor_button_success tve_editor_button_small tve_right tvo-existing-shortcode-template">
				<?php echo __( 'Load display', TVO_TRANSLATE_DOMAIN ); ?>
			</div>
		</div>
	</div>
</div>
