<div class="tvd-modal-content">
	<h4><?php echo __( 'Are you sure you want to archive this variation?', Thrive_Quiz_Builder::T ) ?></h4>

	<p><?php echo __( 'This will move the form to the archive.',Thrive_Quiz_Builder::T ) ?></p>
</div>
<div class="tvd-modal-footer">
	<div class="tvd-row">
		<div class="tvd-col tvd-s12 tvd-m6">
			<a href="javascript:void(0)" class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-modal-close tvd-waves-effect"><?php echo __( 'Cancel', Thrive_Quiz_Builder::T ) ?></a>
		</div>
		<div class="tvd-col tvd-s12 tvd-m6">
			<a href="javascript:void(0)" class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-red tvd-right tvd-modal-submit tve-confirm-delete-action"><?php echo __( 'Move to Archive', Thrive_Quiz_Builder::T ) ?></a>
		</div>
	</div>
</div>
