<div class="tvd-modal-content">
	<h4><?php echo __( 'Sorry, the last variation cannot be archived.', Thrive_Quiz_Builder::T ) ?></h4>
	<# if( page_model.get('post_type') === ThriveQuizB.data.quiz_structure_item_types.results.key ){ #>
		<p><?php echo __( 'If you want to archive the page element, please create another one first.', Thrive_Quiz_Builder::T ) ?></p>
	<# }else{ #>
		<p><?php echo __( 'If you want to remove the page element, please remove it from the Quiz Dashboard.', Thrive_Quiz_Builder::T ) ?></p>
	<# } #>
</div>
<div class="tvd-modal-footer">
	<div class="tvd-row">
		<div class="tvd-col tvd-s12 tvd-m6">
			<a href="javascript:void(0)" class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-modal-close tvd-waves-effect"><?php echo __( 'Cancel', Thrive_Quiz_Builder::T ) ?></a>
		</div>
		<div class="tvd-col tvd-s12 tvd-m6">
			<# if( page_model.get('post_type') !== ThriveQuizB.data.quiz_structure_item_types.results.key ){ #>
				<a href="#dashboard/quiz/<#= page_model.get('post_parent') #>" class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-red tvd-right tvd-modal-submit tve-confirm-delete-action"><?php echo __( 'Quiz Dashboard', Thrive_Quiz_Builder::T ) ?></a>
			<# } #>
		</div>
	</div>
</div>
