<div class="tvd-modal-content">
	<a href="javascript:void(0)" class="tvd-modal-action tvd-modal-close tvd-modal-close-x">
		<i class="tvd-icon-close2"></i>
	</a>
	<h3 class="tvd-modal-title">
		<?php echo __( 'Quiz shortcode ', Thrive_Quiz_Builder::T ); ?>
	</h3>
	<p class="tqb-expl-text"><?php echo __( 'Copy and paste this shortcode in your content to display the quiz.', Thrive_Quiz_Builder::T ) ?></p>
	<div class="tvd-row tvd-copy-row">
		<div class="tvd-col tvd-l6 tvd-m5">
			<div class="tvd-input-field tve-shortcode-input">
				<input readonly="readonly" class="tvd-no-margin tvd-copy" type="text" value="<#= item.getCode() #>"/>
			</div>
		</div>
		<div class="tvd-col tvd-l3 tvd-m4">
			<a class="tvd-copy-to-clipboard tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-purple tvd-btn-small" data-tvd-btn-color-class="tvd-btn-purple" href="javascript:void(0)">
				<span class="tvd-copy-text"><?php echo __( 'Copy', Thrive_Quiz_Builder::T ) ?></span>
			</a>
		</div>
	</div>
</div>
<div class="tvd-modal-footer">
	<div class="tvd-modal-footer">
		<div class="tvd-row">
			<div class="tvd-col tvd-s12 tvd-m6">
				<a href="javascript:void(0)"
				   class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-waves-effect tvd-modal-close">
					<?php echo __( 'Cancel', Thrive_Quiz_Builder::T ) ?>
				</a>
			</div>
			<div class="tvd-col tvd-s12 tvd-m6">
				<a href="javascript:void(0)"
				   class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green tvd-right tvd-modal-close">
					<?php echo __( 'Done', Thrive_Quiz_Builder::T ) ?>
				</a>
			</div>
		</div>
	</div>
</div>

