<div class="tvd-modal-content">
	<h4><?php echo __( 'Warning: You are about to delete Form: ', Thrive_Quiz_Builder::T ) ?> &laquo; <em>
			<#= model.get('post_title') #>
		</em> &raquo; </h4>

	<p><?php echo __( 'You will lose the design and all conversion data associated with this form. This can\'t be undone. ', Thrive_Quiz_Builder::T ) ?></p>
</div>
<div class="tvd-modal-footer">
	<div class="tvd-row">
		<div class="tvd-col tvd-s12 tvd-m6">
			<a href="javascript:void(0)" class="tvd-btn-flat tvd-btn-flat-primary tvd-btn-flat-light tvd-modal-close tvd-waves-effect"><?php echo __( 'Cancel', Thrive_Quiz_Builder::T ) ?></a>
		</div>
		<div class="tvd-col tvd-s12 tvd-m6">
			<a href="javascript:void(0)"
			   class="tvd-waves-effect tvd-waves-light tvd-btn-flat tvd-btn-flat-primary tvd-btn-flat-light tvd-right tvd-modal-submit tve-confirm-delete-action"><?php echo __( 'Delete Form', Thrive_Quiz_Builder::T ) ?></a>
		</div>
	</div>
</div>
