<div class="tqb-modal-step">
	<div class="tvd-modal-content">
		<h3 class="tvd-modal-title">
			<?php echo __( 'Quiz Style', Thrive_Quiz_Builder::T ) ?>
			<a href="<?php echo Thrive_Quiz_Builder::VIDEO_QUIZ_STYLES; ?>" class="wistia-popover[height=450,playerColor=2bb914,width=800]"><span class="tvd-icon-play tqb-purple-icon"></span></a>
		</h3>
		<p><?php echo __( 'Choose a style for your quiz', Thrive_Quiz_Builder::T ) ?>:</p>
		<hr>
		<div id="tqb-quiz-styles-list"></div>
	</div>

	<div class="tvd-modal-footer">
		<div class="tvd-row">
			<div class="tvd-col tvd-s12 tvd-m6">
				<a href="javascript:void(0)"
				   class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-waves-effect tvd-modal-close">
					<?php echo __( 'Back', Thrive_Quiz_Builder::T ) ?>
				</a>
			</div>
			<div class="tvd-col tvd-s12 tvd-m6">
				<a href="javascript:void(0)"
				   class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green tvd-right tqb-modal-next-step tvd-modal-submit">
					<?php echo __( 'Choose Style', Thrive_Quiz_Builder::T ) ?>
				</a>
			</div>
		</div>
	</div>
</div>
