<div class="tqb-modal-step">
	<div class="tvd-modal-content">
		<h3 class="tvd-modal-title"><?php echo __( 'Create a quiz from scratch or customize a template', Thrive_Quiz_Builder::T ) ?></h3>
		<p><?php echo __( 'Choose a template', Thrive_Quiz_Builder::T ) ?>:</p>

		<div class="tqb-new-quiz-templates tvd-row tvd-collapse"></div>
		<div class="tqb-new-quiz-description tvd-row tvd-collapse"></div>
	</div>
	<div class="tvd-modal-footer">
		<div class="tvd-row">
			<div class="tvd-col tvd-s12 tvd-m6">
				<a href="javascript:void(0)"
				   class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-waves-effect tvd-modal-close">
					<?php echo __( 'Cancel', Thrive_Quiz_Builder::T ) ?>
				</a>
			</div>
			<div class="tvd-col tvd-s12 tvd-m6">
				<a href="javascript:void(0)"
				   class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green tvd-right tqb-modal-next-step" disabled="disabled">
					<?php echo __( 'Continue', Thrive_Quiz_Builder::T ) ?>
				</a>
			</div>
		</div>
	</div>
</div>

<div class="tqb-modal-step">
	<div class="tvd-modal-content">
		<h3 class="tvd-modal-title"><?php echo __( 'Label your quiz', Thrive_Quiz_Builder::T ) ?></h3>

		<p><?php echo __( 'Enter a name for your quiz. This is for internal use only - your website visitors will not see this name.', Thrive_Quiz_Builder::T ) ?></p>

		<div class="tvd-input-field">
			<input id="tqb-new-quiz-name" type="text" name="new-quiz-name" data-bind="post_title">
			<label for="tqb-new-quiz-name" data-error="<?php echo __( 'Quiz name is required', Thrive_Quiz_Builder::T ) ?>"><?php echo __( 'Quiz name', Thrive_Quiz_Builder::T ) ?></label>
		</div>
	</div>
	<div class="tvd-modal-footer">
		<div class="tvd-row">
			<div class="tvd-col tvd-s12 tvd-m6">
				<a href="javascript:void(0)"
				   class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-waves-effect tqb-modal-prev-step">
					<?php echo __( 'Back', Thrive_Quiz_Builder::T ) ?>
				</a>
			</div>
			<div class="tvd-col tvd-s12 tvd-m6">
				<a href="javascript:void(0)"
				   class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green tvd-right tvd-modal-submit">
					<?php echo __( 'Continue', Thrive_Quiz_Builder::T ) ?>
				</a>
			</div>
		</div>
	</div>
</div>
