<div class="tqb-modal-step">
	<div class="tvd-modal-content">
		<p class="tqb-user-email"><#= model.get('email')? model.get('email'): model.get('ip_address') #></p>
		<ul class="tvd-collection" id="tqb-user-quiz-answers-list"></ul>
	</div>

	<div class="tvd-modal-footer">
		<div class="tvd-row">
			<div class="tvd-col tvd-s12 tvd-m12">
				<a href="javascript:void(0)"
				   class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green tvd-right tvd-modal-close">
					<?php echo __( 'Close', Thrive_Quiz_Builder::T ) ?>
				</a>
			</div>
		</div>
	</div>
</div>
