<div class="tvd-row" id="tqb-completion-pagination"></div>
<ul class="tvd-collection tvd-with-header" id="tqb-table-items">
	<li class="tvd-collection-header">
		<div class="tvd-row">
			<div class="tvd-col tvd-s4">
				<div class="tvd-truncate-on-small" data-popup="<?php echo __( 'Date interval', Thrive_Quiz_Builder::T ); ?>">
					<h5 class="tvd-truncate-on-small-el">
						<?php echo __( 'Date interval', Thrive_Quiz_Builder::T ); ?>
					</h5>
				</div>
			</div>
			<div class="tvd-col tvd-s4">
				<div class="tvd-truncate-on-small" data-popup="<?php echo __( 'Quiz Name', Thrive_Quiz_Builder::T ); ?>">
					<h5 class="tvd-truncate-on-small-el">
						<?php echo __( 'Quiz Name', Thrive_Quiz_Builder::T ); ?>
					</h5>
				</div>
			</div>
			<div class="tvd-col tvd-s4">
				<div class="tvd-truncate-on-small" data-popup="<?php echo __( 'Completions', Thrive_Quiz_Builder::T ); ?>">
					<h5 class="tvd-truncate-on-small-el">
						<?php echo __( 'Completions', Thrive_Quiz_Builder::T ); ?>
					</h5>
				</div>
			</div>
		</div>
	</li>
</ul>
