<div class="tvd-row">
	<div class="tvd-relative">
		<div id="tqb-chart-container"></div>
		<div class="tve-chart-overlay" style="display: none">
			<div class="tvd-card tvd-small tvd-white tvd-valign-wrapper">
				<div class="tvd-card-content tvd-valign tvd-center-align">
					<h3><?php echo __( 'No Test Data (Yet)', Thrive_Quiz_Builder::T ); ?></h3>
					<p>
						<?php echo __( 'Here you will see a graph of conversion data as the test progresses.<br/> Currently there is no data to display.', Thrive_Quiz_Builder::T ); ?>
					</p>
				</div>
			</div>
		</div>
		<div class="tvd-v-spacer vs-2"></div>
		<div class="tqb-table-container"></div>
	</div>
</div>
