<div class="tqb-flow-report-title-holder">

	<div class="tqb-flow-report-title">
			<h3 class="tvd-title"><?php echo __( 'Flow Report', Thrive_Quiz_Builder::T ) ?></h3>
	</div>
	<# if( item.get('since') ) { #>
		<div class="tqb-flow-report-since">
			<p class="tvd-title"><?php echo __( 'Data collected since latest saved quiz structure: ', Thrive_Quiz_Builder::T ) ?>
				<span><#= item.get('since') #></span>
			</p>
		</div>

	<# } #>

</div>

<div class="tqb-flow-report-container tvd-col tvd-s12">
	<div class="tqb-flow-report-splash "></div>
	<div class="tqb-flow-report-qna "></div>
	<div class="tqb-flow-report-optin "></div>
	<div class="tqb-flow-report-results "></div>
</div>

<div class="tqb-flow-report-conclusion">

	<div class="tqb-flow-report-title-holder">
		<p><?php echo __( 'Summary', Thrive_Quiz_Builder::T ) ?></p>
	</div>

	<div class="tqb-flow-report-content">
		<div id="tqb-quiz-completions">
			<p>
				<#= item.get('completions') #>
			</p>
			<p>
				<?php echo __( 'Quiz Completions', Thrive_Quiz_Builder::T ) ?>
			</p>
			<p>
				<#= item.get('users')? ( ( item.get('completions') * 100 ) / item.get('users') ).toFixed(2): 0 #>% <?php echo __( 'of Visitors', Thrive_Quiz_Builder::T ) ?>
			</p>
		</div>
		<div id="tqb-quiz-shares">
			<p>
				<#= item.get('results_social_shares') #>
			</p>
			<p>
				<?php echo __( 'Social shares', Thrive_Quiz_Builder::T ) ?>
			</p>
			<p>
				<#= item.get('users')? ( ( item.get('results_social_shares') * 100 ) / item.get('users') ).toFixed(2): 0 #>% <?php echo __( 'of Visitors', Thrive_Quiz_Builder::T ) ?>
			</p>
		</div>
		<div id="tqb-quiz-conversions">
			<p>
				<#= item.get('users')? ( Number( item.get('results_subscribers') ) + Number( item.get('optin_subscribers') ) ): 0  #>
			</p>
			<p>
				<?php echo __( 'Subscriptions', Thrive_Quiz_Builder::T ) ?>
			</p>
			<p><#= item.get('users')? ( ( ( Number( item.get('results_subscribers') ) + Number( item.get('optin_subscribers') ) ) * 100 ) / item.get('users') ).toFixed(2): 0 #>% <?php echo __( 'of Visitors', Thrive_Quiz_Builder::T ) ?></p>
		</div>
	</div>
</div>
