<?php
$quizzes = TQB_Quiz_Manager::get_quizzes(); ?>
<div id="tve-content">
	<div id="tve-reporting">
		<h3>
			<?php echo __( 'Reporting', Thrive_Quiz_Builder::T ); ?>
		</h3>
		<div class="tvd-v-spacer vs-2"></div>
		<form>
			<div class="tvd-row">
				<div class="tvd-col tvd-s5 tvd-m2">
					<div class="tvd-input-field">
						<select name="report_type" id="tqb-report-type">
							<option value="completions"><?php echo __( 'Quiz Completions', Thrive_Quiz_Builder::T ); ?></option>
							<option value="flow"><?php echo __( 'Flow', Thrive_Quiz_Builder::T ); ?></option>
							<option value="questions"><?php echo __( 'Questions', Thrive_Quiz_Builder::T ); ?></option>
							<option value="users"><?php echo __( 'Users', Thrive_Quiz_Builder::T ); ?></option>
						</select>
						<label for="tqb-report-type"><?php echo __( 'Show report', Thrive_Quiz_Builder::T ); ?></label>
					</div>
				</div>
				<div class="tvd-col tvd-s5 tvd-m2">
					<div class="tvd-input-field">
						<div id="tqb-report-source-container"></div>
					</div>
				</div>
				<div class="tqb-secondary-selectors" style="display:none;">
					<div class="tvd-col tvd-s5 tvd-m2">
						<div class="tve-chart-interval">
							<div class="tvd-input-field">
								<select autocomplete="off" id="tqb-chart-date-select" name="tqb-date-interval">
									<option selected
									        value="<?php echo Thrive_Quiz_Builder::TQB_LAST_7_DAYS; ?>"><?php echo __( 'Last 7 days', Thrive_Quiz_Builder::T ); ?></option>
									<option
										value="<?php echo Thrive_Quiz_Builder::TQB_LAST_30_DAYS; ?>"><?php echo __( 'Last 30 days', Thrive_Quiz_Builder::T ); ?></option>
									<option
										value="<?php echo Thrive_Quiz_Builder::TQB_THIS_MONTH; ?>"><?php echo __( 'This month', Thrive_Quiz_Builder::T ); ?></option>
									<option
										value="<?php echo Thrive_Quiz_Builder::TQB_LAST_MONTH; ?>"><?php echo __( 'Last month', Thrive_Quiz_Builder::T ); ?></option>
									<option
										value="<?php echo Thrive_Quiz_Builder::TQB_THIS_YEAR; ?>"><?php echo __( 'This year', Thrive_Quiz_Builder::T ); ?></option>
									<option
										value="<?php echo Thrive_Quiz_Builder::TQB_LAST_YEAR; ?>"><?php echo __( 'Last year', Thrive_Quiz_Builder::T ); ?></option>
									<option
										value="<?php echo Thrive_Quiz_Builder::TQB_LAST_12_MONTHS; ?>"><?php echo __( 'Last 12 months', Thrive_Quiz_Builder::T ); ?></option>
									<option
										value="<?php echo Thrive_Quiz_Builder::TQB_CUSTOM_DATE_RANGE; ?>"><?php echo __( 'Custom date range', Thrive_Quiz_Builder::T ); ?></option>

								</select>
								<label for="tqb-chart-date-select"><?php echo __( 'Date interval', Thrive_Quiz_Builder::T ); ?>:</label>
							</div>
						</div>
					</div>
					<div class="tvd-col tvd-s6 tvd-m4 tqb-custom-filter">
						<div class="tvd-row tvd-collapse tvd-no-margin">
							<div class="tvd-col tvd-s5">
								<div class="tvd-input-field">
									<input type="text" name="tve-report-start-date" id="tqb-report-start-date" class=""/>
									<label for="tve-report-start-date"><?php echo __( 'Start date', Thrive_Quiz_Builder::T ); ?></label>
								</div>
							</div>
							<div class="tvd-col tvd-s1 tvd-center-align">
								<span class="tvd-icon-calendar start-date-calendar calendar-trigger-icon" data-activates="#tqb-report-start-date"></span>
							</div>
							<div class="tvd-col tvd-s5">
								<div class="tvd-input-field">
									<input type="text" name="tve-report-end-date" id="tqb-report-end-date" class=""/>
									<label for="tve-report-end-date"><?php echo __( 'End date', Thrive_Quiz_Builder::T ); ?></label>
								</div>
							</div>
							<div class="tvd-col tvd-s1 tvd-center-align">
								<span class="tvd-icon-calendar end-date-calendar calendar-trigger-icon" data-activates="#tqb-report-end-date"></span>
							</div>
						</div>
					</div>
					<div class="tvd-col tvd-s5 tvd-m2">
						<div class="tve-chart-interval">
							<div class="tvd-input-field">
								<select autocomplete="off" id="tqb-chart-interval-select" name="tqb-chart-interval">
									<option selected value="day"><?php echo __( 'Daily', Thrive_Quiz_Builder::T ); ?></option>
									<option value="week"><?php echo __( 'Weekly', Thrive_Quiz_Builder::T ); ?></option>
									<option value="month"><?php echo __( 'Monthly', Thrive_Quiz_Builder::T ); ?></option>
								</select>
								<label for="tve-chart-interval-select"><?php echo __( 'Graph interval', Thrive_Quiz_Builder::T ); ?>:</label>
							</div>
						</div>
					</div>
				</div>

				<div class="tvd-col tvd-s2 tvd-m8">&nbsp;</div>
			</div>
		</form>
		<div class="tqb-reporting-content tvd-row" id="tqb-report-content"></div>
	</div>
	<div class="tvd-v-spacer vs-2"></div>
	<div class="tvd-row">
		<div class="tvd-col tvd-s6">
			<a class="tvd-btn-flat tvd-btn-flat-primary tvd-btn-flat-dark tvd-waves-effect"
			   href="#dashboard" title="<?php echo __( 'Back to Quiz Dashboard', Thrive_Quiz_Builder::T ) ?>"
			   id="tve-asset-group-dashboard">&laquo;<?php echo __( 'Back to Quiz Dashboard', Thrive_Quiz_Builder::T ) ?>
			</a>
		</div>
	</div>
	<div class="tvd-v-spacer vs-2"></div>
</div>
