<div class="tqb-flow-report-title">
	<div class="tvd-row tvd-collapse">
		<div class="tvd-col tvd-s6">
			<h3 class="tvd-title"><?php echo __( 'Questions Report', Thrive_Quiz_Builder::T ) ?></h3>
		</div>
	</div>
</div>
<div class="tqb-questions-container"></div>
<div class="tqb-questions-report-no-data" style="display:none;">
	<span><?php echo __( 'No data recorded for this quiz', Thrive_Quiz_Builder::T ) ?> </span>
</div>
