<div class="tvd-row">
	<div class="tvd-col tvd-s1" >
		<span class="tqb-answer-color" style="background-color:<#= item.get('color') #>" ></span>
	</div>
	<div class="tvd-col tvd-s7" style="color:<#= item.get('color') #>">
		<# if( item.get('image') ) { #>
			<img height="100" src="<#= item.get('image')#>" alt="" class="tqb-answer-image">
			<# } else { #>
				<#= item.get('text') #>
				<# } #>
	</div>
	<div class="tvd-col tvd-s2">
		<#= item.get('count') #>
	</div>
	<div class="tvd-col tvd-s2">
		<#= item.get('percent') #>%
	</div>
</div>