<# if(item.get('total_items')) { #>
<div class="tqb-users-list-table">
	<div class="tvd-row tvd-collapse">
		<div class="tvd-col tvd-s12">
			<h3 class="tvd-title"><?php echo __( 'Users report', Thrive_Quiz_Builder::T ) ?></h3>
		</div>
	</div>
	<div class="tvd-row tvd-collapse">
		<div class="tvd-col tvd-s12">
			<h5>
				<span class="tqb-users-list-item-number"><#= item.get('total_items') #></span>
				<span><?php echo __( 'items', Thrive_Quiz_Builder::T ) ?></span>
			</h5>
		</div>
	</div>
	<table class="tvd-collection tvd-with-header tvd-not-fixed-table">
		<thead>
		<tr class="tvd-collection-header ">
			<td>
				<h5>
					<?php echo __( 'Item', Thrive_Quiz_Builder::T ) ?>
				</h5>
			</td>
			<td class="tqb-users-list-connection tvd-center-align" style="min-width: 110px;">
				<h5>
					<?php echo __( 'Date and Start Time', Thrive_Quiz_Builder::T ) ?>
				</h5>
			</td>
			<td class="tqb-users-list-date ">
				<h5>
					<?php echo __( 'E-mail address', Thrive_Quiz_Builder::T ) ?>
				</h5>
			</td>
			<td class="tqb-users-list-date ">
				<h5>
					<?php echo __( 'IP Address', Thrive_Quiz_Builder::T ) ?>
				</h5>
			</td>
			<td class="tvd-center-align  ">
				<h5>
					<?php echo __( 'Quiz result', Thrive_Quiz_Builder::T ) ?>
				</h5>
			</td>
			<td class="tvd-center-align ">
				<h5>
					<?php echo __( 'Generated Social Badge', Thrive_Quiz_Builder::T ) ?>
				</h5>
			</td>
			<td class="tvd-center-align ">
				<h5>
					<?php echo __( 'Answers', Thrive_Quiz_Builder::T ) ?>
				</h5>
			</td>
		</tr>
		</thead>
		<tbody class="tqb-users-list-table-content">

		</tbody>
		<tfoot>
		<tr class="tvd-collection-item">
			<td colspan="5" >
				<div class="tvd-right">
					<p class="tvd-inline-block tvd-small-text tvd-no-margin">
						<strong>
							<?php echo __( 'Rows per page', Thrive_Quiz_Builder::T ) ?>
						</strong>
					</p>
					<div class="tvd-input-field tvd-inline-block tvd-input-field-small tvd-no-margin">
						<select class="" id="tqb-user-per-page" tabindex="-1"
						        aria-hidden="true">
							<option value="5">5</option>
							<option value="10">10</option>
							<option value="15">15</option>
							<option value="20">20</option>
						</select>
					</div>
					<span class="tvd-inline-block tvd-margin-left"></span>
				</div>
			</td>
			<td colspan="1" >
				<div class="tvd-right">
					<div class="tqb-users-report-jump">
						<p class="tvd-inline-block tvd-small-text tvd-no-margin">
							<strong>
								<?php echo __( 'Jump to page', Thrive_Quiz_Builder::T ) ?>
							</strong>
						</p>
						<div class="tvd-input-field tvd-inline-block">
							<input class="tvd-jump-to-page tvd-no-margin tvd-input-field-small" type="text" name="current_page"
							       data-error="<?php echo __( 'Page doesn\'t exist', Thrive_Quiz_Builder::T ) ?>"
							       id="tqb-current-page-input" value="<#= item.get('jump_page') #>">
						</div>
						<a class="tqb-jump-to-page-button tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-blue tvd-btn-small tvd-margin-left-small"
						   href="javascript:void(0)" tabindex="1"><?php echo __( 'Go', Thrive_Quiz_Builder::T ) ?></a>
					</div>
				</div>
			</td>
			<td colspan="2">
				<div class="tvd-pagination-container tqb-users-report-pagination">
					<p class="tvd-inline-block tvd-small-text">
						<strong>
							<?php echo __( 'Page', Thrive_Quiz_Builder::T ) ?>
							<span class="tqb-users-list-current-page"><#= item.get('current_page') #></span>&nbsp;
							<?php echo __( 'of', Thrive_Quiz_Builder::T ) ?>&nbsp;
							<span class="tqb-users-list-total-pages"><#= item.get('total_pages') #></span>
						</strong>
					</p>
					<a class="tqb-previous-page tvd-text-gray tvd-margin-left" href="javascript:void(0)"><span
							class="tvd-icon-chevron-left"></span></a>
					<a class="tqb-next-page tvd-text-gray tvd-margin-left" href="javascript:void(0)"><span
							class="tvd-icon-chevron-right2"></span></a>
				</div>
			</td>
		</tr>
		</tfoot>
	</table>
</div>
<# } else { #>
	<div class="tqb-no-users-in-report"><?php echo __( 'No users completed this quiz', Thrive_Quiz_Builder::T ) ?></div>
<# } #>


