<div class="tvd-col tvd-s3">
	<span class="tho-vertical-align">
		<#= test.winner_title #>
	</span>
</div>

<div class="tvd-col tvd-s2 tvd-center-align">
	<span class="tho-vertical-align">
		<#= test.date_started #>
	</span>
</div>

<div class="tvd-col tvd-s2 tvd-center-align">
	<span class="tho-vertical-align">
		<#= test.date_completed #>
	</span>
</div>

<div class="tvd-col tvd-s2 tvd-center-align">
	<span class="tho-vertical-align">
		<#= test.views #>
	</span>
</div>

<div class="tvd-col tvd-s2 tvd-center-align">
	<span class="tho-vertical-align">
		<#= test.engagements #>
	</span>
</div>

<div class="tvd-col tvd-s1">
	<a class="tvd-btn-icon tvd-btn-icon-blue" href="#test/<#=test.id#>">
		<span class="tho-icon-link"></span><span class="tvd-on-large-and-down"><?php echo __( 'View test', THO_TRANSLATE_DOMAIN ); ?></span>
	</a>
</div>