<div class="tho-container">
	<div class="tvd-row">
		<h3 class="tvd-left tvd-title tvd-margin-right">
			<?php echo __( 'Content With Currently Active Tests', THO_TRANSLATE_DOMAIN ); ?>
		</h3>
		<a class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-blue tve-add-group tvd-left"
		   href="<?php echo admin_url( 'admin.php?page=tho_admin_dashboard' ); ?>#createTest/selectPosts"
		   title="<?php echo __( 'Add new' ) ?>" id="tve-lead-add">
			<?php echo __( 'Add new', THO_TRANSLATE_DOMAIN ); ?>
		</a>
	</div>
	<div class="tvd-row">
		<p><?php echo __( 'It looks like you haven’t used our headline split testing feature before. Click on the "Add New" button to start a new test. For help, watch our video below.', THO_TRANSLATE_DOMAIN ); ?></p>
	</div>
	<div class="tvd-center-align tvd-row">
		<a href="//fast.wistia.net/embed/iframe/09xa7i2pok?popover=true" class="wistia-popover[height=450,playerColor=2bb914,width=800]">
			<img src="<?php echo THO_ADMIN_URL . "/img/tho-getting-started-thumbnail.png" ?>" alt=""/>
		</a>
	</div>
</div>