<div class="tvd-card tvd-white">
	<div class="tvd-card-content tie-badge-card" style="<#= item.get_bg_style() #>"></div>
	<div class="tvd-card-action">
		<h4><?php echo __( 'Social Badge Created' ) ?></h4>
		<div class="tqb-pull-right">
			<a id="tqb-remove-badge" href="javascript:void(0)">
				<i class="tvd-icon-trash-o"></i>
				<?php echo __( 'Remove', Thrive_Quiz_Builder::T ) ?>
			</a>
			<a class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-purple tvd-btn-small" href="<#= item.get('editor_url') #>">
				<?php echo __( 'Edit', Thrive_Quiz_Builder::T ) ?>
			</a>
		</div>
	</div>
</div>
