<div class="tvd-card tvd-red tvo-medium tvo-delete-shortcode-card tvd-valign-wrapper" tabindex="-1">
	<div class="tvd-card-content tvd-center-align">
		<h4 class="tvd-margin-top">
			<?php echo __( 'Are you sure you want to delete this shortcode?', TVO_TRANSLATE_DOMAIN ) ?>
		</h4>
	</div>
	<div class="tvd-card-action">
		<div class="tvd-row tvd-no-mb">
			<div class="tvd-col tvd-s12 tvd-m6">
				<a class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-light tvd-left tvo-delete-yes">
					<?php echo __( 'Yes, delete', TVO_TRANSLATE_DOMAIN ) ?>
				</a>
			</div>
			<div class="tvd-col tvd-s12 tvd-m6">
				<a class="tvd-btn-flat tvd-btn-flat-primary tvd-btn-flat-light tvd-right tvo-delete-no">
					<?php echo __( 'No, keep it', TVO_TRANSLATE_DOMAIN ) ?>
				</a>
			</div>
		</div>
	</div>
</div>
