<div class="tvd-container">
	<div class="tvd-row">
		<div class="tvd-col tvd-s12">
			<h3 class="tvd-title tvd-left tvd-margin-right"><?php echo __( 'Testimonial <#= type #> shortcodes', TVO_TRANSLATE_DOMAIN ); ?></h3>
			<a href="javascript:void(0);"
			   class="tvo-add-new-shortcode tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-blue tvd-left"><?php echo __( 'Add New', TVO_TRANSLATE_DOMAIN ); ?></a>

		</div>
	</div>
	<div class="tvd-row tvo-shortcodes-notice" style="display: none">
		<div class="tvd-col tvd-s12">
			<p>
				<?php echo __( 'You haven\'t yet built any shortcodes to <#= type #> testimonial on your site. ', TVO_TRANSLATE_DOMAIN ); ?>
				<a href="//fast.wistia.net/embed/iframe/<#= (type=='display'?'aphg8wwb77':'dixw38l8kz') #>?popover=true" class="wistia-popover[height=450,playerColor=2bb914,width=800]"><?php echo __( 'Watch this video to get started.', TVO_TRANSLATE_DOMAIN ); ?></a>
			</p>
		</div>
	</div>
	<div class="tvd-row tvd-no-margin tvo-shortcodes-container">
		<div class="tvd-col tvd-s6 tvd-ms6 tvd-m4 tvd-l3 tvo-add-new-shortcode">
			<div class="tvd-card tvo-medium tvd-card-new tvd-valign-wrapper">
				<div class="tvd-card-content tvd-valign tvd-center-align tvd-pointer">
					<i class="tvd-icon-plus tvd-icon-rounded tvd-icon-medium"></i>
					<h4>
						<?php echo __( 'New <#= type #> shortcode', TVO_TRANSLATE_DOMAIN ); ?>
					</h4>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="tvd-row">
	<div class="tvd-col tvd-s6">
		<a class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-gray" href="#testimonials">Back to Dashboard</a>
	</div>
</div>

