<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    'OTGS\\Toolset\\Maps\\Bootstrap' => $baseDir . '/application/Bootstrap.php',
    'OTGS\\Toolset\\Maps\\Controller\\Compatibility\\MapBlock' => $baseDir . '/application/controllers/compatibility/gutenberg/editor-blocks/blocks/map/mapBlock.php',
    'OTGS\\Toolset\\Maps\\Controller\\Compatibility\\MapsEditorBlockFactory' => $baseDir . '/application/controllers/compatibility/gutenberg/editor-blocks/blocks/factory.php',
    'OTGS\\Toolset\\Maps\\Controller\\Compatibility\\MapsEditorBlocks' => $baseDir . '/application/controllers/compatibility/gutenberg/editor-blocks/editor-blocks.php',
    'OTGS\\Toolset\\Maps\\Model\\Distance\\Calculator' => $baseDir . '/application/models/Distance/Calculator.php',
    'OTGS\\Toolset\\Maps\\Model\\Shortcode\\Distance\\ConditionalDisplay' => $baseDir . '/application/models/Shortcode/Distance/ConditionalDisplay.php',
    'OTGS\\Toolset\\Maps\\Model\\Shortcode\\Distance\\Value' => $baseDir . '/application/models/Shortcode/Distance/Value.php',
    'OTGS\\Toolset\\Maps\\Model\\Shortcode\\ShortcodeAbstract' => $baseDir . '/application/models/Shortcode/ShortcodeAbstract.php',
    'OTGS\\Toolset\\Maps\\Model\\Shortcode\\ShortcodeInterface' => $baseDir . '/application/models/Shortcode/ShortcodeInterface.php',
    'Toolset_Addon_Maps_CRED' => $baseDir . '/includes/toolset-maps-cred.class.php',
    'Toolset_Addon_Maps_Common' => $baseDir . '/includes/toolset-common-functions.php',
    'Toolset_Addon_Maps_Types' => $baseDir . '/includes/google_address.php',
    'Toolset_Addon_Maps_Views' => $baseDir . '/includes/toolset-maps-views.class.php',
    'Toolset_Addon_Maps_Views_Distance_Filter' => $baseDir . '/includes/toolset-views-maps-distance-filter.php',
    'Toolset_Maps_Geolocation_Shortcode' => $baseDir . '/includes/toolset-maps-geolocation-shortcode.php',
    'Toolset_Maps_Location' => $baseDir . '/includes/toolset-maps-location.php',
    'Toolset_Maps_Location_Factory' => $baseDir . '/includes/toolset-maps-location-factory.php',
    'Toolset_Maps_Shortcode_Generator' => $baseDir . '/includes/toolset-maps-shortcode-generator.php',
    'Toolset_Maps_Views_Distance' => $baseDir . '/includes/toolset-maps-views-distance.php',
    'Toolset_Maps_Views_Distance_Order' => $baseDir . '/includes/toolset-maps-views-distance-order.php',
    'WPToolset_Field_google_address' => $baseDir . '/includes/toolset-maps-types.class.php',
);
