<div class="tvd-card tvd-red tvd-large tvd-valign-wrapper tvd-slim-card tve-delete-quiz-card" tabindex="-1">
	<div class="tvd-card-content tvd-center-align tvd-valign">
		<h4 class="tvd-margin-top">
			<?php echo __( 'Are you sure you want to delete' . ' ' . '<#= item.attributes.post_title #>' . ' ' . 'and all its data??', Thrive_Quiz_Builder::T ) ?>
		</h4>
	</div>
	<div class="tvd-card-action">
		<div class="tvd-buttons-container">
			<div class="tvd-button-holder">
				<a class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-light tqb-delete-yes">
					<?php echo __( 'Yes, delete', Thrive_Quiz_Builder::T ) ?>
				</a>
			</div>
			<div class="tvd-button-holder">
				<a class="tvd-btn-flat tvd-btn-flat-primary tvd-btn-flat-light tqb-delete-no">
					<?php echo __( 'No, keep it', Thrive_Quiz_Builder::T ) ?>
				</a>
			</div>
		</div>
	</div>
</div>
