<div class="tqb-container">
	<div class="tqb-left tqb-quiz-name-holder">
		<span><?php echo __( 'Quiz name:', Thrive_Quiz_Builder::T ) ?></span>
		<div class="tqb-edit-title-container">
			<h3 class="tqb-quiz-title">
				<#= item.get('post_title') #>
			</h3>
			<span class="tvd-icon-pencil tvd-pointer tqb-edit-quiz-title tvd-inline-block"></span>
		</div>
	</div>
	<div class="tqb-right tqb-shortcode-holder tvd-copy-row">
		<p class="tqb-shortcode-highlight">Quiz Shortcode:</p>
		<div class="tvd-input-field tve-shortcode-input">
			<input readonly="readonly" class="tvd-copy" type="text" value="<#= item.getCode() #>"/>
		</div>
		<div class="tqb-shortcode-button">
			<a class="tvd-copy-to-clipboard tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-purple tvd-btn-small" data-tvd-btn-color-class="tvd-btn-purple" href="javascript:void(0)">
				<span class="tvd-copy-text"><?php echo __( 'Copy', Thrive_Quiz_Builder::T ) ?></span>
			</a>
		</div>
	</div>
</div>


<div class="tvd-row" id="tqb-quiz-configuration-row">
	<div class="tvd-col tvd-s12 tvd-m4 tvd-l4 tqb-relative-tooltip-position">
		<div class="tvd-card">
			<div class="tqb-left tqb-logo-holder">
				<i class="tqb-gray-text tqb-large-icon tqb-score-quiz" id="<#= item.attributes.type #>"></i>
			</div>
			<div class="tqb-right tqb-info-holder">
				<div class="tvd-card-content">
					<span class="tvd-truncate"><?php echo __( 'Quiz Type:', Thrive_Quiz_Builder::T ) ?></span>
					<span class="tqb-quiz-type"><#= item.get('quiz_type_label') #></span><br>
					<span class="tqb-quiz-card-summary">
						<#= item.get('quiz_type_text') #>
					</span>
					<p class="tqb-quiz-description"><?php echo __( 'Choose the type of evaluation you want for your quiz', Thrive_Quiz_Builder::T ) ?>.</p>
				</div>
				<div class="tvd-card-action">
					<a class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-purple tvd-btn-small tqb-edit-quiz-type" href="javascript:void(0)">
						<# if( item.get('type') ){ #>
							<# if( item.get('type') == ThriveQuizB.data.quiz_types.personality && ( item.get( 'page_variations' ) > 0 || item.get( 'structure' ).tge_question_number ) ){ #>
							<?php echo __( 'Manage results', Thrive_Quiz_Builder::T ) ?>
							<# } else { #>
								<?php echo __( 'Change type', Thrive_Quiz_Builder::T ) ?>
							<# } #>
						<# } else { #>
							<?php echo __( 'Choose type', Thrive_Quiz_Builder::T ) ?>
						<# } #>
					</a>
					<# 	if ( item.get_settings_step() === 'type' ) { #>
						<div class="tvd-tooltip-visible tvd-fixed-bottom tvd-normalize tqb-wizard-tooltip tqb-edit-quiz-type" href="javascript:void(0)">
							<span><?php echo __( 'Step 1/4: Select a quiz type.', Thrive_Quiz_Builder::T ) ?></span>
						</div>
					<# } #>
				</div>
			</div>
		</div>
	</div>
	<div class="tvd-col tvd-s12 tvd-m4 tvd-l4 tvd-pointer" id="tqb-quiz-style-card"></div>
	<div class="tvd-col tvd-s12 tvd-m4 tvd-l4 tvd-pointer" id="tqb-badge-card"></div>
</div>

<div class="tvd-row" id="tqb-quiz-structure-row"></div>

<div class="tvd-v-spacer vs-2"></div>
<div class="tvd-row">
	<div class="tvd-col tvd-s6">
		<a href="#dashboard" class="tvd-btn-flat tvd-btn-flat-primary tvd-btn-flat-dark tvd-waves-effect">
			&laquo; <?php echo __( 'Back to Dashboard', Thrive_Quiz_Builder::T ) ?>
		</a>
	</div>
</div>
<div class="tvd-v-spacer vs-2"></div>
