<div class="tvd-card tvd-white">
	<div class="tvd-card-content">
		<div class="tqb-container">
			<p class="tvd-truncate tvd-no-margin"><?php echo __( 'Quiz Structure', Thrive_Quiz_Builder::T ) ?></p>
		</div>
		<hr>
		<div class="tvd-row tvd-no-margin tvd-valign-wrapper">
			<div class="tvd-col tvd-s12 tvd-ms12 tvd-valign">
				<div id="tqb-structure-card-container">
					<div id="tqb-structure-card-splash"></div>
					<div id="tqb-structure-card-qna"></div>
					<div id="tqb-structure-card-optin"></div>
					<div id="tqb-structure-card-results"></div>
				</div>
				<div class="tvd-col tvd-s12 tvd-m3 tvd-no-margin tvd-valign tvd-right" id="tqb-structure-button-wrapper">
					<div class="tvd-row" id="tqb-structure-button-container">
						<p class="tqb-pages-info"><?php echo __( 'Add more pages', Thrive_Quiz_Builder::T ) ?></p>
						<div class="" id="tqb-structure-button-splash"></div>
						<div class="" id="tqb-structure-button-qna"></div>
						<div class="" id="tqb-structure-button-optin"></div>
						<div class="" id="tqb-structure-button-results"></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
