<div class="tve_p_right" id="tqb-thrv-label">
	<a href="<?php echo Thrive_Quiz_Builder::PLUGIN_SALES_PAGE; ?>" target="_blank">
		<span>
			<?php echo __( 'powered by', Thrive_Quiz_Builder::T ) ?>&nbsp;
		</span>
		<span class="tqb-bold">
			<?php echo __( 'Thrive', Thrive_Quiz_Builder::T ) ?>&nbsp;
		</span>
		<span>
			<?php echo __( 'Quiz Builder', Thrive_Quiz_Builder::T ) ?>
		</span>
	</a>
</div>
