<div class="tqb-question-container">

	<div class="tqb-question-text">
		<#= item.get('text') #>
	</div>

	<# if (item.get('description') ) { #>
		<div class="tqb-question-description">
			<#= item.get('description') #>
		</div>
	<# } #>

	<# if (item.get('image') ) { #>
		<div class="tqb-question-image-container">
			<img src="<#= item.get_image() #>" alt="question-image">
		</div>
	<# } #>

</div>
<div class="tqb-answers-container"></div>
