<td>
	<span class="tqb-variation-title"><#= item.get('post_title') #></span>
	<a href="javascript:void(0)" class="tqb-edit-variation-title">
		<span class="tvd-icon-pencil"></span>
	</a>
	<# if (item.get('is_control') == 1) { #>
		(<?php echo __( 'control', Thrive_Quiz_Builder::T ) ?>)
	<# } #>
</td>
<# if (item.get('is_control') == 0) { #>
	<td colspan="<# if( page_model.get('post_type') === ThriveQuizB.data.quiz_structure_item_types.results.key ){ #>5<# }else{ #>3<# } #>">
		<div class="inline-message">
			<?php echo __( 'No traffic is currently being sent to this form. Start an A/B Test to start tracking statistics', Thrive_Quiz_Builder::T ) ?>
		</div>
	</td>
<# }else{ #>
	<td>
		<#= item.get('cache_impressions') #>
	</td>
	<td>
		<#= item.get('cache_optins_conversions') #>
	</td>
	<td>
		<#= item.get('cache_optin_conversion_rate') #>
	</td>
	<# if( page_model.get('post_type') === ThriveQuizB.data.quiz_structure_item_types.results.key ){ #>
		<td>
			<#= item.get('cache_social_shares_conversions') #>
		</td>
		<td>
			<#= item.get('cache_social_share_conversion_rate') #>
		</td>
	<# } #>
<# } #>

<td class="table-row-actions">
	<div class="tvd-right">
		<# if( item.get('is_default') && ( page_model.get('variations').length <= 1 ) ){ #>
			<a href="<#= item.get('tcb_editor_url') #>" target="_blank"  class="tvd-btn-icon-solid tvd-btn-icon-solid-blue tqb-position-relative">
				<div class="tvd-tooltip-visible tvd-fixed-bottom tvd-normalize tqb-wizard-tooltip tqb-edit-variation-tooltip" href="javascript:void(0)">
					<span><?php echo __( 'This is your default content. Click here to edit the design.', Thrive_Quiz_Builder::T ) ?></span>
				</div>
				<i class="tvd-icon-pencil"></i>
			</a>
		<# } else { #>
			<a href="<#= item.get('tcb_editor_url') #>" target="_blank"  class="tvd-btn-icon-solid tvd-btn-icon-solid-blue tvd-tooltipped tqb-position-relative" data-tooltip="<?php echo __( 'Edit Design', Thrive_Quiz_Builder::T ); ?>" data-position="top">
				<i class="tvd-icon-pencil"></i>
			</a>
		<# } #>
		<a href="javascript:void(0)" class="tvd-btn-icon-solid tvd-btn-icon-solid-purple tvd-tooltipped tqb-variation-clone" data-tooltip="<?php echo __( 'Clone', Thrive_Quiz_Builder::T ); ?>" data-position="top">
			<i class="tvd-icon-clone2"></i>
		</a>
		<a href="javascript:void(0)" class="tvd-btn-icon-solid tvd-btn-icon-solid-orange tvd-tooltipped tqb-variation-reset" data-tooltip="<?php echo __( 'Reset Stats', Thrive_Quiz_Builder::T ); ?>" data-position="top">
			<i class="tvd-icon-undo"></i>
		</a>
		<a href="javascript:void(0)" class="tvd-btn-icon-solid tvd-btn-icon-solid-teal tvd-tooltipped tqb-variation-archive" data-tooltip="<?php echo __( 'Archive', Thrive_Quiz_Builder::T ); ?>" data-position="top">
			<i class="tvd-icon-box-add"></i>
		</a>
	</div>
</td>
