<# 	var settings = model,
	general_settings = true; #>
<div class="tvd-modal-content">
<div class="tvd-row">
	<div class="tvd-col tvd-s12">
		<h3 class="tvd-title">
			<?php echo __( "Settings", THO_TRANSLATE_DOMAIN ); ?>
		</h3>
		<div class="tvd-v-spacer"></div>
			<?php include THO_PATH . 'admin/views/template/settings/content_engagement_settings.phtml';?>
		</div>
</div>
</div>
<div class="tvd-modal-footer">
	<div  class="tvd-row">
		<div class="tvd-col tvd-s12">
			<a href="javascript:void(0);" class="tvd-waves-effect tho-save-settings tvd-waves-light tvd-btn tvd-btn-green tvd-right"><?php echo __( "Save", THO_TRANSLATE_DOMAIN  ); ?></a>
		</div>
	</div>
</div>
