<div class="tvd-modal-content">
	<ul class="tvd-collection tvd-with-header tho-stop-test-variations">
		<li class="tvd-row tvd-collection-header">
			<div class="tvd-col tvd-s4">
				<div class="tvd-truncate-on-small" data-popup="<?php echo __( 'Headline', THO_TRANSLATE_DOMAIN ); ?>">
					<h5 class="tvd-truncate-on-small-el">
						<?php echo __( 'Headline', THO_TRANSLATE_DOMAIN ); ?>
					</h5>
				</div>
			</div>
			<div class="tvd-col tvd-s1">
				<div class="tvd-truncate-on-small" data-popup="<?php echo __( 'Content views', THO_TRANSLATE_DOMAIN ); ?>">
					<h5 class="tvd-truncate-on-small-el">
						<?php echo __( 'Content views', THO_TRANSLATE_DOMAIN ); ?>
					</h5>
				</div>
			</div>
			<div class="tvd-col tvd-s1">
				<div class="tvd-truncate-on-small" data-popup="<?php echo __( 'Engagements', THO_TRANSLATE_DOMAIN ); ?>">
					<h5 class="tvd-truncate-on-small-el">
						<?php echo __( 'Engagements', THO_TRANSLATE_DOMAIN ); ?>
					</h5>
				</div>
			</div>
			<div class="tvd-col tvd-s1">
				<div class="tvd-truncate-on-small" data-popup="<?php echo __( 'Engagement rate', THO_TRANSLATE_DOMAIN ); ?>">
					<h5 class="tvd-truncate-on-small-el">
						<?php echo __( 'Engagement rate', THO_TRANSLATE_DOMAIN ); ?>
					</h5>
				</div>
			</div>
			<div class="tvd-col tvd-s1">
				<div class="tvd-truncate-on-small" data-popup="<?php echo __( 'Percentage improvement', THO_TRANSLATE_DOMAIN ); ?>">
					<h5 class="tvd-truncate-on-small-el">
						<?php echo __( 'Percentage improvement', THO_TRANSLATE_DOMAIN ); ?>
					</h5>
				</div>
			</div>
			<div class="tvd-col tvd-s2">
				<div class="tvd-truncate-on-small" data-popup="<?php echo __( 'Chance to beat original', THO_TRANSLATE_DOMAIN ); ?>">
					<h5 class="tvd-truncate-on-small-el">
						<?php echo __( 'Chance to beat original', THO_TRANSLATE_DOMAIN ); ?>
					</h5>
				</div>
			</div>
			<div class="tvd-col tvd-s2">
				&nbsp;
			</div>
		</li>
	</ul>
</div>
<div class="tvd-modal-footer">
	<div class="tvd-row">
		<div class="tvd-col tvd-s12">
			<a class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-modal-close tvd-waves-effect"
			   href="javascript:void(0)">
				<?php echo __( 'Cancel', THO_TRANSLATE_DOMAIN ) ?>
			</a>
		</div>
	</div>
</div>