<div class="tvd-modal-content">
	<a href="javascript:void(0)" class="tvd-modal-action tvd-modal-close tvd-modal-close-x">
		<i class="tvd-icon-close2"></i>
	</a>
	<p class="tvd-center-align ">
			<span class="tvd-nm-small-icon">
				<?php echo __( 'Are you sure you want to stop showing the variation:', THO_TRANSLATE_DOMAIN ); ?>
			</span>
	</p>
	<p class="tvd-modal-title tvd-center-align">
		<strong>"<span class="tvd-nm-small-icon"><#= variation_title #></span>"</strong>
	</p>
</div>
<div class="tvd-modal-footer">
	<div class="tvd-row">
		<div class="tvd-col tvd-s12 tvd-m6">
			<a href="javascript:void(0)"
			   class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-light tvd-modal-close tvd-waves-effect">
				<?php echo __( 'KEEP IT RUNNING', THO_TRANSLATE_DOMAIN ); ?>
			</a>
		</div>
		<div class="tvd-col tvd-s12 tvd-m6">
			<a href="javascript:void(0)"
			   class="tvd-waves-effect tvd-waves-light tvd-btn-flat tvd-btn-flat-primary tvd-btn-flat-light tvd-right tve-confirm-delete-action tho-stop-test-variation-modal-action">
				<?php echo __( 'STOP', THO_TRANSLATE_DOMAIN ); ?>
			</a>
		</div>
	</div>
</div>
