<div class="tvd-blue tho-xsmall tvd-center-align">
	<div class="tho-icon-check tho-xlarge-icon tvd-white-text"></div>
</div>
<div class="tvd-modal-content">
	<div class="tvd-center-align">
		<h3 class="tho-text-blue-gray tvd-normal">
			<?php echo __( 'Test completed!', THO_TRANSLATE_DOMAIN ); ?>
		</h3>
		<div class="tvd-v-spacer vs-3"></div>
		<div class="tho-winning-cup">
			<div class="tho-winning-percentage">
				<#= percentage #>
			</div>
		</div>
		<div class="tvd-v-spacer vs-2"></div>
		<h3 class="tvd-normal tho-text-gray">
			<#= winner #>
		</h3>
	</div>
</div>
<div class="tvd-modal-footer">
	<div class="tvd-row">
		<div class="tvd-col tvd-s6 tvd-offset-s3">
			<a class="tvd-modal-close tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green tvd-full-btn" href="javascript:window.location.reload();">
				<?php echo __( 'GO TO TEST REPORT', THO_TRANSLATE_DOMAIN ) ?>
			</a>
		</div>
	</div>
</div>