<div class="tvd-modal-content">
	<a href="javascript:void(0)" class="tvd-modal-action tvd-modal-close tvd-modal-close-x">
		<i class="tvd-icon-close2"></i>
	</a>
	<h3 class="tvd-modal-title"><?php echo __( 'Warning' ) ?></h3>
	<p class="tvo-modal-text">
		<?php echo __( 'Another approval email has been sent to the author of this testimonial. Are you sure you want to send another one?', TVO_TRANSLATE_DOMAIN ); ?>
	</p>
</div>
<div class="tvd-modal-footer">
	<div class="tvd-row">
		<div class="tvd-col tvd-s12">
			<a class="tvo-send-approval-email tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green tvd-right"
			   href="javascript:void(0);"><?php echo __( 'Yes, send email', TVO_TRANSLATE_DOMAIN ); ?></a>
			</a>
			<a class="tvd-modal-close tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-gray tvd-margin-right tvd-right"
			   href="javascript:void(0);"><?php echo __( 'No, don\'t send', TVO_TRANSLATE_DOMAIN ); ?></a>
			</a>
		</div>
	</div>
</div>
