<ul class="tvd-collection tvd-with-header"  id="tho-table-items">
	<li class="tvd-collection-header">
		<div class="tvd-row">
			<div class="tvd-col tvd-s6">
				<div class="tvd-truncate-on-small" data-popup="<?php echo __( 'Date', THO_TRANSLATE_DOMAIN ); ?>">
					<h5 class="tvd-truncate-on-small-el"><?php echo __( 'Date', THO_TRANSLATE_DOMAIN ); ?></h5>
				</div>
			</div>
			<div class="tvd-col tvd-s6">
				<div class="tvd-truncate-on-small" data-popup="<?php echo __( 'Engagements rate', THO_TRANSLATE_DOMAIN ); ?>">
					<h5 class="tvd-truncate-on-small-el"><?php echo __( 'Engagements rate', THO_TRANSLATE_DOMAIN ); ?></h5>
				</div>
			</div>
		</div>
	</li>
</ul>