<div class="tvd-col tvd-s1 tvd-center-align">
		<span class="tge-sort-handle tvd-move">
			<span class="tvd-icon-handle"></span>
		</span>
</div>

<div class="tvd-col tvd-s2 tge-image-loader tvd-center-align"></div>

<div class="tvd-col tvd-s4">
    <div class="tvd-input-field">
        <input class="tge-answer-text" id="tge-qf-answer-<#= item.cid #>" data-bind="text" type="text" value="<#= item.get('text') #>">
        <label for="tge-qf-answer-<#= item.cid #>"><?php echo __( 'Optional description', Thrive_Graph_Editor::T ) ?></label>
    </div>
</div>

<div class="tvd-col tvd-s4 tge-points-column">
    <div class="tvd-input-field">
        <input id="tge-qf-points-<#= item.cid #>" data-bind="points" type="text" maxlength="6" value="<#= item.get('points') #>">
        <label for="tge-qf-points-<#= item.cid #>">
            <#= TGE_Editor.quiz.quiz_type === 'personality' ? 'Weight' : 'Points' #>
        </label>
    </div>
</div>

<div class="tvd-col tvd-s1 tvd-right-align">
    <span class="tvd-icon-trash-o tvd-pointer" data-id="<#= item.cid #>"></span>
</div>
