<div class="tvd-right">
	<span class="tvd-inline-block"><strong><?php echo __('Rows per page:',THO_TRANSLATE_DOMAIN); ?></strong></span>
	<div class="tvd-input-field tvd-input-field-small tvd-inline-block tho-paginatin-select">
		<select class="tho-items-per-page">
			<option value="10" <# if(itemsPerPage == 10) { #> selected="selected"  <# } #>>10</option>
					<option value="15" <# if(itemsPerPage == 15) { #> selected="selected"  <# } #>>15</option>
							<option value="30" <# if(itemsPerPage == 30) { #> selected="selected"  <# } #>>30</option>
									<option value="50" <# if(itemsPerPage == 50) { #> selected="selected"  <# } #>>50</option>
		</select>
	</div>

	<div class="tho-total-new-leads tvd-inline-block ">
		<strong>
			<#= (currentPage-1)*itemsPerPage #> - <#= currentPage * itemsPerPage > total_items ? total_items : currentPage * itemsPerPage #>
					<?php echo __('of',THO_TRANSLATE_DOMAIN) ?>   <#= total_items #>
		</strong>
	</div>

	<div id="pages" class="tvd-inline-block ">
		<# if( pageCount > 1) { #>
			<a <# if(currentPage > 1) { #> href="#" class="page" value="<#= currentPage - 1 #>" <# } #>> <span class="tho-icon-chevron-left tho-icon-pagination"></span> </a>
						<a <# if(currentPage < pageCount) { #> href="#" class="page" value="<#= (currentPage + 1) #>" <# } #>> <span class="tho-icon-chevron-right tho-icon-pagination"></span> </a>
								<# } #>
	</div>
</div>